repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear', mccabe, 'pep8-naming']
      args: ['--max-complexity=5']
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ['--profile=black']
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: ['--ignore=D100,D104,D203,D205,D209,D213,D400,D415',
            '--match=deeprecsys/rl/.*']
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --disallow-untyped-calls, --disallow-untyped-defs, --disallow-incomplete-defs]
        additional_dependencies: [types-attrs]
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      language_version: python3
      exclude: ^deeprecsys/tests/
      args: ['-q', '--ignore-nosec', '-s', 'B608,B303']

