repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, jupyter]
      - id: ruff-format
        types_or: [python, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --disallow-untyped-calls,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
          ]
        additional_dependencies: [types-attrs]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.6.2"
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^deeprecsys/tests/
        args: ["-q", "--ignore-nosec", "-s", "B608,B303,B101"]
