name: Master Deploy

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.37.1
      - name: Install dependencies and test
        run: |
          task setup
          venv/bin/poetry run pre-commit uninstall
          task test
      - name: Upload Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate Documentation
        run: |
          task docs
      - name: Version Bump
        run: |
          task bump
          git push
          git push origin v$(task version)
      - name: Build package and publish
        env:
          PYPI_KEY: ${{ secrets.PYPI_KEY }}
        run: |
          task publish
      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Publishing release v$(task version)"
          gh release create v$(task version) --repo ${REPO_NAME} --title v$(task version) --generate-notes