name: Master Deploy

on:
  push:
    branches:    
      - 'master'

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.6'
    - name: Install dependencies and test
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run coverage run -m pytest
    - name: Generate Documentation
      run: |
        poetry run coverage html -d docs/coverage
        poetry run pdoc --html --force deeprecsys -o docs/api
    - name: Version Bump
      run: |
        poetry version patch
        git config --global user.name 'Github Actions'
        git config --global user.email 'luksfarris@users.noreply.github.com'
        git commit -am "Bump to version $(poetry version -s)"
        git push
    - name: Build package and publish
      run: |
        poetry build
        poetry config pypi-token.pypi ${{ secrets.PYPI_KEY }}
        poetry publish
